### ISSUE TITLE
address input ENS lookup fails on first try. works after

### ISSUE THREAD

**Issue by evvvritt** [radicle-dev/drips-app-v2#132]
1. open Edit Splits
2. enter `goerli.eth` on GOERLI (gives error)
3. focus into second address input, enter `goerli.eth` (resolves)
4. (reload app to repeat effect)

<img width="1553" alt="Screen Shot 2022-11-29 at 12 53 09" src="https://user-images.githubusercontent.com/6071219/204522236-3e0d1aa1-39aa-48eb-a297-86e4c8ca2433.png">

**Comment by efstajas** [comment]
Resolves #128
