### ISSUE TITLE
fix MetaMask switch account event

### ISSUE THREAD

**Issue by evvvritt** [radicle-dev/drips-app-v2#137]
a user can switch their connected account inside MetaMask, and our app should react to this change properly:

1. dashboard sections does not update
2. token page should redirect to current wallet's token page, otherwise redirect

**Comment by efstajas** [comment]
Maybe as a quick fix we could just reload the app for now, same as when network changes? I'd be worried about what would happen if e.g. a modal is currently open, and some of the state may not be reactive to the current user. Maybe also some signer or SDK instance is initialized somewhere and not refreshed on wallet address change. We could probably support a seamless switch, but we would have to test super extensively.
