### ISSUE TITLE
handle app awaiting locked wallet (metamaks / brave)

### ISSUE THREAD

**Issue by evvvritt** [radicle-dev/drips-app-v2#153]
When refreshing app / dashboard, it initializes and tries to reconnect to cached provider, if wallet is locked the app is blank.

Not entirely sure if app knows what the situation is though.

**Comment by efstajas** [comment]
At least now the loading state appears while this is happening:

<img width="898" alt="image" src="https://user-images.githubusercontent.com/1018218/205113997-498bf7a5-85fb-4abf-9c31-b8fe473cab5a.png">

But yeah, we should definitely add a "Please unlock your wallet" state. Can use the new `global-advisory` store for this 👍
