### ISSUE TITLE
Use a ? icon for unknown token logos

### ISSUE THREAD

**Issue by efstajas** [radicle-dev/drips-app-v2#155]
Currently, tokens without a logo are shown with an ( i ) symbol which is just a placeholder because we don't have a ( ? ) icon in the design system.

<img width="224" alt="Screenshot 2022-12-01 at 17 38 15" src="https://user-images.githubusercontent.com/1018218/205109023-4a88104f-3f25-4ae7-addf-48eaafd4e42e.png">

**Comment by brandonhaslegs** [comment]
I think instead of a ? icon, it should be an icon based on the name of the token. Check out how Rainbow does it:
![IMG_1514](https://user-images.githubusercontent.com/4406983/205271419-7954c41b-b267-47fb-acfe-074c640b4c56.jpeg)

**Comment by efstajas** [comment]
Closing in favor of #161
