### ISSUE TITLE
Enhancement - Allow "add max" for topping up the outgoing balance

### ISSUE THREAD

**Issue by bordumb** [radicle-dev/drips-app-v2#159]
## Overview

It's fairly common/standard for there to be a "max" option when setting up some sending of funds

We could add the following:

<img width="588" alt="image" src="https://user-images.githubusercontent.com/3743841/205144728-32af99ec-4057-4eee-a361-71ed91d6398c.png">

> Note: it may be worth adding this wherever it makes sense. This is just the first place I thought of it.

**Comment by efstajas** [comment]
Another place where something similar makes sense is the withdraw flow, which #124 is for. Should probably resolve both in one swoop.
