### ISSUE TITLE
Enhancement - WETH icon is confusing

### ISSUE THREAD

**Issue by bordumb** [radicle-dev/drips-app-v2#161]
## Problem

The current WETH icon is confusing because this small "i" icon is typically used for tooltips and represents "i" for "information"

So it looks like it should be some sort of icon that will have a tooltip if hovered over/clicked.

<img width="110" alt="image" src="https://user-images.githubusercontent.com/3743841/205148340-304ce37e-c38b-4cd9-a319-cbf49c1a7427.png">

## Proposal

We change this default token icon to something else.

**Comment by bordumb** [comment]
See Metamask's little "i" tooltip below

<img width="343" alt="image" src="https://user-images.githubusercontent.com/3743841/205148589-fb574756-5b76-4030-8215-e105f5ffdc34.png">

**Comment by brandonhaslegs** [comment]
I think instead of a ? icon, it should be an icon based on the name of the token. Check out how Rainbow does it:
![IMG_1514](https://user-images.githubusercontent.com/4406983/205271419-7954c41b-b267-47fb-acfe-074c640b4c56.jpeg)

**Comment by brandonhaslegs** [comment]
What about the last four characters of the contract address?

**Comment by brandonhaslegs** [comment]
Anyway, if you must, here is your question mark icon https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/%F0%9F%8C%B1-Radicle?node-id=13780%3A225944&t=Hgrw7uMzkXYjted2-4

**Comment by brandonhaslegs** [comment]
I still think it’s fine.

**Comment by efstajas** [comment]
So, I'd do this:

- Display symbol in circle if we don't have a logo but know symbol
- Display ( ? ) for unknown custom tokens. IMO the last 4 chars of the contract address is a bit meaningless and could add more confusion.

Cool?

**Comment by brandonhaslegs** [comment]
And if we dont have a sumbol but we do have a ticker name, then dispay the ticker name in the circle. RAD ETH BTC etc

**Comment by efstajas** [comment]
Ah sorry, "symbol" in this context means "ticker name".

**Comment by efstajas** [comment]
Hey, so here's what I did:

If we know a token and it doesn't have an image (or loading the image failed), it generates an icon using the token's `symbol`:
<img width="527" alt="Screenshot 2022-12-02 at 17 31 33" src="https://user-images.githubusercontent.com/1018218/205340136-1ce53704-f44e-4f81-b091-27be8e9491a1.png">

The background color of the icon is randomly selected from an array of possible colors, using the token address as a seed — so for the same token, it'll be consistent across clients. @brandonhaslegs right now it's just using basic CSS colors `['red', 'green', 'blue', 'purple']`. Lmk if you want to use a different array of possible colors here, but let's only choose colors on which white text is legible.

If there is very little space and a long symbol, it will only display the first letter:
<img width="604" alt="Screenshot 2022-12-02 at 17 33 48" src="https://user-images.githubusercontent.com/1018218/205340557-4eff33dc-fb65-4c98-a528-a6a28eab4f02.png">

Unknown tokens, for which we only know the address, are displayed with the question mark icon Brandon made, dark grey on a light grey background.

Next thing I don't have a strong opinion on — but to avoid "WETH — WETH" from showing up as the title on the token page, I opted to display the full name of the token as the headline of the token page, and show symbols next to the amounts across the page:

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/1018218/205341075-42bf82e3-731d-46de-a8cc-84d624f8b70d.png">

@evvvritt wdyt? Happy to keep that as-is if you feel strongly.

Does that match everyone's expectations?

**Comment by brandonhaslegs** [comment]
> background color of the icon is randomly selected from an array of possible colors, using the token address as a seed

sounds good. if possible try to keep the Saturation high and Brightness down. so they don’t get too muddy. random colors can get ugly fast.

> Unknown tokens, for which we only know the address, are displayed with the question mark icon

I think this is weird. it might seem like something is wrong, like there’s an action a user needs to take. i think it should feel more neutral. But you don’t show it in your mock up so not really sure. Maybe could just be a filled grey circle

> it will only display the first letter

it could fit 4 characters. seems weird to show the ticker symbol on 3 letter ones but only show the first letter for 4 letter ones. the letters will get really small but i think it’s fine if it’s slightly illegible.

>  add the token name on the token page

looks good

**Comment by efstajas** [comment]
Alright, removed the 1-letter logic thing, it now always tries to fit the entire symbol into the icon 👍
