### ISSUE TITLE
Bug - Cannot highlight -> copy/paste ENS names 

### ISSUE THREAD

**Issue by bordumb** [radicle-dev/drips-app-v2#163]
## Problem

If you are on someone's profile page and they have an ENS name, if you double-click it, it will not high-light / let you copy and paste it.

<img width="468" alt="image" src="https://user-images.githubusercontent.com/3743841/205152702-9156f5e3-8ddb-47a0-a532-2ddf879a8aff.png">

Some examples:
https://drips-app-v2.vercel.app/app/drippy.eth
https://drips-app-v2.vercel.app/app/0xE26B30aB0bdaf3f187A76BC831408167f4184113

## Proposal

Make it possible to double-click the ENS name to copy/paste

## Why this is important

There are 2 workarounds:
* Manually enter the ENS name -> can lead to human error 
* Select the profile icon and swipe/high-light, which works -> but it's also prone to human error in improperly high lighting to copy/paste 

Double-clicking test to high-light -> copy/paste is the most robust way to properly copy/paste content.

Given we're dealing with peoples' finances, we should probably make sure there won't be any human error

**Comment by efstajas** [comment]
For sure. You can already copy the full address from someone's profile today, but beyond that; we already have the tooltip component with a copy-able mode. I think best solution would be to just make all the identity components have a tooltip with the full address + copy icon.
