### ISSUE TITLE
Cannot create stream

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/drips-app-v2#166]
The "Create stream" button is always inactive despite the form being filled out:

![image](https://user-images.githubusercontent.com/26183680/205285105-a8b78216-06b1-4747-a290-2d6d81e53777.png)

**Comment by efstajas** [comment]
The problem here is that you didn't click to select a token — this is really unclear. Will pre-select the first token in the list, that should make it clearer.

**Comment by CodeSandwich** [comment]
Aaah, that's right, this was it!
