### ISSUE TITLE
Empty splits list icon

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/drips-app-v2#170]
Why is it a skull? It's not dangerous or harmful to not split, probably something less loaded and more neutral would be more appropriate. (When did I become such a boring person?)

**Comment by evvvritt** [comment]
i had bubbles before 🫧
which i thought was funny as like, differing amounts of 0

**Comment by brandonhaslegs** [comment]
It’s supposed to be bubbles. I made a bubbles illustration.
