### ISSUE TITLE
Drips setup modal doesn't show amount unit unless the token name is clicked

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/drips-app-v2#173]

**Comment by efstajas** [comment]
Ah, I think the problem is that the "Token" selector doesn't look like a selector if there's only one token, right? Do you think pre-selecting the only token if there's only one would solve this problem?

**Comment by CodeSandwich** [comment]
Sorry, I should've included screenshots. In my case it **is** preselected, so this part works like a charm, it's just that it doesn't affect the amount field:

![image](https://user-images.githubusercontent.com/26183680/205289812-1973256e-0599-4f40-a6ec-b0739f85ed71.png)

After I click "Wrapped Ether":

![image](https://user-images.githubusercontent.com/26183680/205290059-081c3ce3-19b8-4ddc-92cf-190d0ecfb0a3.png)

You're right that WETH is the only token which I've topped-up.

**Comment by efstajas** [comment]
This UI is quite confusing — I think we're still misunderstanding each other :D 

The token selector is a list of all available tokens, and you have to click on one to select it:

<img width="715" alt="image" src="https://user-images.githubusercontent.com/1018218/205292268-bc8dc27a-edaa-4f4a-b75b-8bad8bbb9157.png">

It's the same component as in the "Add token" flow, except with the search bar disabled when there's less than 5 available tokens. It's not a dropdown or something, ergo the initial state of it just displaying the first token is not it being selected.

I've opened #178 which should alleviate this confusion by just always pre-selecting the first token in the list.
