### ISSUE TITLE
The pixelated fonts

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/drips-app-v2#175]
The main page has some texts pixelated. They pose some problems:
- They're poorly readable. If you hover, it's even worse, it keeps changing and some steps of the animation are too pixelated to read at all.
- The hover animation shifts around surrounding text, which looks amateurishly.

Personally I find the pixelated, italic font unaesthetic, but that's totally my subjective feeling, feel free to ignore it.

**Comment by efstajas** [comment]
@brandonhaslegs #96 is closed but the effect is still there, did you decide to keep it after all?

**Comment by brandonhaslegs** [comment]
I thought I removed it? It’s not here anymore at least https://drips-app-v2.vercel.app/

**Comment by efstajas** [comment]
huh we're talking about the pixel font effect when hovering over e.g. "Ethereum" in the headline, right? It's definitely still there for me

**Comment by brandonhaslegs** [comment]
Yeah on my browser it gone. But on two other browsers it’s there. No idea. I’ve opened a PR #182 to remove it.

**Comment by efstajas** [comment]
Fixed in #182

**Comment by brandonhaslegs** [comment]
This issue isn’t technically fixed. The issue was that the fonts are not readable. Are we deciding to ignore that? I vote to ignore it, I do think they’re readable and only used in headline situations, which is fine.

**Comment by efstajas** [comment]
My bad! 

I like the aesthetic for sure, I think it adds a lot of character, but I definitely second the readability concern. What if we just tone down the pixelation one or two levels?

**Comment by brandonhaslegs** [comment]
Yeah we had that at one point but I like this style better.

Maybe we should just choose a nice serif font?

**Comment by efstajas** [comment]
Or that, ya. I delegate my vote to you :)

**Comment by CodeSandwich** [comment]
There are a ton of stylish yet legible pixelart fonts. If we want to go with the pixels, we probably should use one of them instead of forcing an unfit, regular font to get low-res.

**Comment by efstajas** [comment]
It is a font specifically designed to be low-res. https://www.redaction.us/

**Comment by efstajas** [comment]
I mean, it's an aesthetic choice, i don't think it's about using the "right" or "wrong tools". Redaction is made by world-class typographers 🤷‍♂️ Anyway, its specifically designed to become increasingly illegible at increasing pixellation levels, that's the whole idea behind it, which is why I agree that legibility is a concern. But whether it's more or less "aesthetic" than some other font is I think highly subjective 😄

**Comment by brandonhaslegs** [comment]
Gonna close this because that is how the cookie has crumbled.
