### ISSUE TITLE
Glitchy Globe Illustration

### ISSUE THREAD

**Issue by efstajas** [radicle-dev/drips-app-v2#202]
<img width="590" alt="Screenshot 2022-12-06 at 10 43 23" src="https://user-images.githubusercontent.com/1018218/205876139-bf6a2c7c-a50f-426c-a74a-a935541eae6a.png">

**Comment by brandonhaslegs** [comment]
I also fixed this but I think I did it at the wrong time and it didn't get merged in. 😬
