### ISSUE TITLE
Splits section

### ISSUE THREAD

**Issue by efstajas** [radicle-dev/drips-app-v2#23]
The Splits section displays the current account's splits configuration in a visual representation by default. The user may also switch over to a table list view of their splits. If a lot of splits are present, or some splits are too small to be represented in the visual bar view, it automatically switches to the table list view.

Designs: https://www.figma.com/file/vyI7f996JF8zwhnXwAwXdC/Drips-App-V2?node-id=169%3A5354

![Image](https://user-images.githubusercontent.com/1018218/191025036-77b00bef-2156-4094-9345-da37a8c80523.png)

**Comment by evvvritt** [comment]
revised to use flow lines design, and can expand to see all rows/amounts on click


![Image](https://user-images.githubusercontent.com/6071219/194083853-e4be0dbc-7697-45a1-80f2-73d4a9de7528.png)
