### ISSUE TITLE
"drips sticker" on mobile covers "made by radicle"

### ISSUE THREAD

**Issue by efstajas** [radicle-dev/drips-app-v2#250]
Let's left-align the "made by radicle" on mobile?

<img width="382" alt="Screenshot 2022-12-19 at 15 32 58" src="https://user-images.githubusercontent.com/1018218/208449279-b68e1a0b-066a-4bcb-ba87-eba820657e84.png">

**Comment by brandonhaslegs** [comment]
I think it’s kinda cool that it covers it
