### ISSUE TITLE
Bug - Streams component chopped off on Balances Details page

### ISSUE THREAD

**Issue by bordumb** [radicle-dev/drips-app-v2#257]
## Overview

When visiting the Balances Details page, the bottom component looks like it had its bottom chopped off.

It doesn't match the other components, so looks inconsistent/off.

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/3743841/209235674-17631c43-be5a-499d-a119-e072c7ed8513.png">

Example:
https://drips-app-v2-radicle.vercel.app/app/0x380a4Ab8C518596919D5Ef29c367D5EF6cF4A606/tokens/0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6

**Comment by efstajas** [comment]
@bordumb 
<img width="1667" alt="Screenshot 2023-01-04 at 13 59 10" src="https://user-images.githubusercontent.com/1018218/210560284-305f5623-c7b0-4537-b2d5-de04d496c6bc.png">

I'm struggling to reproduce this on my device, even when zooming the page. I suspect this is related to screen resolution and maybe a specific browser engine - would you mind sharing what browser and screen resolution you're using, and what zoom level this happens at?
