### ISSUE TITLE
Feature Request - Simplify adding funds flow 

### ISSUE THREAD

**Issue by bordumb** [radicle-dev/drips-app-v2#259]
## Overview

Adding funds currently takes 3 clicks across 2 modal pages, like so:

![image](https://user-images.githubusercontent.com/3743841/209239320-bd209919-f66b-4828-b700-b0f6c65b01a7.png)

## Proposal

Get rid of the middle modal, like so:

![image](https://user-images.githubusercontent.com/3743841/209239347-999064dd-2ed5-4dde-9e99-52a88782cc6e.png)

## Overarching Thoughts 

IMO we already have too many pages/clicks with crypto, especially when you factor in taking care of all the Metamask pop-ups to finalize transactions.

So minimizing others pages/clicks elsewhere is a nice way to help users with less work/pain.

**Comment by bordumb** [comment]
@efstajas 

> We can not trivially fetch all ERC-20 balances for all the tokens on our token list (200+ on mainnet) unless we were to use some (centralized) API like Alchemy...

This point alone makes me agree with your point that it's probably good to keep it as is.

Out of curiosity, what are we using if we're not using Alchemy? Something like [Pocket Network](https://www.pokt.network/) or something else?

**Comment by efstajas** [comment]
@bordumb Currently, we're just querying the user's balance for a given token directly from its contract: https://github.com/radicle-dev/drips-app-v2/blob/96af3d250a28473450356ccf82e22779d7e2d1d9/src/lib/utils/erc20/fetch-balance.ts#L4-L19
