### ISSUE TITLE
Feature Request - Explicitly link to docs 

### ISSUE THREAD

**Issue by bordumb** [radicle-dev/drips-app-v2#289]
## Overview

There currently isn't a super obvious link to docs anywhere on the site below:
https://drips-app-v2-git-jason-crowdfunding-lp-radicle.vercel.app/app/dashboard

Currently looks like this:
<img width="1497" alt="image" src="https://user-images.githubusercontent.com/3743841/215279424-eef268f3-729b-4354-bea2-e043364aa94f.png">

## Proposal

I'd propose finding a 1-click solution to find docs (i.e. user should not have to click more than once).

I'd say if a user needs to click 3+ times to find docs, they might give up.

**Comment by efstajas** [comment]
@brandonhaslegs wdyt about this?

<img width="416" alt="image" src="https://user-images.githubusercontent.com/1018218/215466725-ff6751ca-fea1-40f2-a07f-349b2d770d70.png">

this would also be the place for adding legal disclaimer stuff once we actually have that ready.

**Comment by brandonhaslegs** [comment]
1. Should it be "Made by Radicle" like on the landing page?
2. The underline under the arrow looks bad. I've done this before but just left the underline under the actual words and left it off the arrows. Requires complicated <span>'s… if you want to make it easier on yourself then just remove the arrows.
3. Would be good to have more context instead of just "Help". Maybe something like "Having trouble? Read the Docs"

**Comment by efstajas** [comment]
@brandonhaslegs 

> Should it be "Made by Radicle" like on the landing page?

On the new LP it says "Supported by Radicle" now, but we can discuss whether it shouldn't, haha.

> The underline under the arrow looks bad

Removed the arrows.

> Would be good to have more context instead of just "Help". Maybe something like "Having trouble? Read the Docs"

Hm, not sure, I feel like a "Help" link in an account menu is quite common?

**Comment by brandonhaslegs** [comment]
> Hm, not sure, I feel like a "Help" link in an account menu is quite common?

Yeah I just mean more text. I think just writing "Help" is weird. Maybe even "🛟 Get help" 

**🛟 Get help • 💸 Supported by Radicle**

jk… or?

**Comment by efstajas** [comment]
OK I'll change it to "Get help" for now 👌
