### ISSUE TITLE
Modal is broke

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/drips-app-v2#388]
<img width="690" alt="image" src="https://user-images.githubusercontent.com/4406983/229112190-4edbf9eb-4d26-4ecf-a0e5-8ffd545cb27d.png">

**Comment by efstajas** [comment]
probably happens if an `await` step resolves very fast. We might just have to artificially slow down to at least 100ms or so.

**Comment by brandonhaslegs** [comment]
Whatever we do, it should be consistent.

<img width="606" alt="image" src="https://user-images.githubusercontent.com/4406983/229114262-252165b0-2827-4d15-93b0-2b623adde1a8.png">

Maybe just copy what everyone else does. Coinbase, Uniswap, Coinmarketcap all seem to force it.

**Comment by efstajas** [comment]
@brandonhaslegs Pretty sure what I did should fix this. If it happens again please feel free to reopen!
