### ISSUE TITLE
Glitchy

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/drips-app-v2#519]
<img width="586" alt="image" src="https://github.com/radicle-dev/drips-app-v2/assets/4406983/e99a43b2-0730-4c12-810e-791d86e67239">

**Comment by efstajas** [comment]
was this during the screenshare? what browser?

**Comment by brandonhaslegs** [comment]
I wasn't screensharing, I was just dragging it around. I think you can ignore it because… no idea what it is. But was using Safari and it was happening consistently

**Comment by efstajas** [comment]
Closing since I can't repro even in Safari; and even if I could I doubt we could influence this, it seems like some kind of graphical glitch on the browser level. If you can consistently reproduce this, feel free to re-open.
