### ISSUE TITLE
Emojis misaligned on Chrome 

### ISSUE THREAD

**Issue by efstajas** [radicle-dev/drips-app-v2#526]
<img width="565" alt="Screenshot 2023-07-10 at 19 04 57" src="https://github.com/radicle-dev/drips-app-v2/assets/1018218/a699ac46-a83e-42e2-bf22-fb1927a2eb4f">

**Comment by efstajas** [comment]
Affects only chrome on MacOS, and seems to depend on the display resolution too. Strangely enough, using Inter as the font for emojis causes them to be aligned properly, but then some of the emojis are replaced with inter's glyphs, which we don't want either. I guess the only real fix would be to start using some third-party emoji set like twemoji everywhere.

@brandonhaslegs wdyt?

**Comment by brandonhaslegs** [comment]
Emojis are gonna display differently on every device anyway, so yeah might as well implement twemojis.

**Comment by efstajas** [comment]
We're using twemoji now 👍
