### ISSUE TITLE
Delayed FUNDING.json state

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/drips-app-v2#534]
When verifying that the repo contains FUNDING.json, GitHub seems to have a delay. I've edited FUNDING.json and for ~30 seconds the app kept receiving the old value. Is there some caching involved? Is it on GitHub side? Their front end gets the updated content immediately, is the externally exposed API inferior?

**Comment by efstajas** [comment]
@jtourkos It looks like the request is being served from disk cache (i can see in my dev tools network tab that it returns 200 "from disk cache" when I retry the funding.json check. Think there's a way to have it not cache locally? 🤔
