### ISSUE TITLE
Should the address already be considered "linked"?

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/drips-app-v2#541]
On this stage of claiming the repo:
![image](https://github.com/radicle-dev/drips-app-v2/assets/26183680/6c64b840-d3e2-4400-a124-8b50b5db578e)
the user is led to believe that the repo is already linked. Is this true at this point? In the current transactions flow it's clearly untrue, because the claiming transaction hasn't been sent yet. In the final flow with a gasless transaction this probably won't be true either, at least not immediately. Will the badge appear only after the oracle sets the on-chain repo ownership? As of now the user may expect that after closing the page the repo will already be claimed.

**Comment by efstajas** [comment]
So with the gasless implementation now done and (almost) merged, I'd say we can definitely keep it that way. While it's true that it's not yet technically "linked" on-chain, 1) it's "linked" off-chain just by the FUNDING.json being there, and 2) the requestOwnerUpdate TX has successfully been sent and is processing in the background by this point, with very little chance of failure.

I'm going to close this issue as resolved for now, but please feel free to re-open if you feel differently!
