### ISSUE TITLE
Setting repo owner as a maintainer

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/drips-app-v2#547]
When configuring splits for a repo from a repo profile, the repo owner address IS NOT by default on the list of maintaners. It IS in the repo claiming flow, and it's very convenient. It'd be awesome to have that in the repo profile splits configuration flow.
![image](https://github.com/radicle-dev/drips-app-v2/assets/26183680/ae2342ca-2a3d-4c02-960a-e4c1673d78a6)

**Comment by efstajas** [comment]
@CodeSandwich Was this one of those partially-claimed repos maybe? Usually, there would always be an existing splits config, and this modal just loads the existing splits initially.

**Comment by CodeSandwich** [comment]
Yes, it was, so I guess that it's not an issue, sorry :sweat_smile:
