### ISSUE TITLE
Initial splits settable only in the repo claiming flow

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/drips-app-v2#549]
I've claimed a repo, but I've aborted the initial setup transaction, I've just returned to the app root. Now the repo profile is claimed, but when I try to set its splits configuration, I get an error:
![image](https://github.com/radicle-dev/drips-app-v2/assets/26183680/6895c693-750c-4083-8946-3e24b4587102)

Looks similar to https://github.com/radicle-dev/drips-app-v2/issues/546, but has a different error, so it might be something else.

**Comment by efstajas** [comment]
It's caused by https://github.com/radicle-dev/drips-app-v2/issues/536, which @jtourkos is working on and should resolve shortly 👍
