### ISSUE TITLE
[enhancement][design] project emoji modal: slightly prefer if emojis + colors aren't greyed out until hover

### ISSUE THREAD

**Issue by evvvritt** [radicle-dev/drips-app-v2#553]
feels disabled + harder to see 

<img width="644" alt="Screenshot 2023-07-12 at 10 23 44" src="https://github.com/radicle-dev/drips-app-v2/assets/6071219/426d535d-a518-48f2-9002-30bc37f7711e">

**Comment by brandonhaslegs** [comment]
I agree!
