### ISSUE TITLE
"Back to drips" link not useful

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/drips-app-v2#555]
Clicking this link:
![image](https://github.com/radicle-dev/drips-app-v2/assets/26183680/68f34cc6-6259-418d-8c6c-8b2e2a932c92)
Is hardcoded to lead to `https://drips.network/`. This isn't very useful, I'd expect to be taken back to the app. It should also lead to the instance of the app which I left off, not necessarily the main one. This page always shows up in a new tab, maybe just closing the current tab would be enought? Maybe this whole page could be a modal? It could be much more convenient.

**Comment by efstajas** [comment]
… I'm gonna close this after all, I think that with it being a) a new tab and b) no longer having the "Back to Drips" button at all, we're in a good place for now.
