### ISSUE TITLE
maybe "getting started" collapsables should go lower?

### ISSUE THREAD

**Issue by evvvritt** [radicle-dev/drips-app-v2#567]
odd "create your first stream" appears when I have a stream to my drip list

maybe these go at the bottom if you have streams?
is "explore the network" still relevant
"collect earnings" should be in Projects?
🤔 

<img width="1624" alt="Screenshot 2023-07-12 at 11 05 35" src="https://github.com/radicle-dev/drips-app-v2/assets/6071219/ad3ae3fb-2010-42bf-9fa5-34e2b250c0d5">

**Comment by efstajas** [comment]
@evvvritt closing this as resolved since this section now shows "claim a project" and "support your dependencies" as the first two cards, which IMO is a lot more relevant on first-open now.
