### ISSUE TITLE
Stream doesn't disappear after stopping

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/drips-app-v2#568]
After stopping a stream support for my drip list, the stream is still visible:
![image](https://github.com/radicle-dev/drips-app-v2/assets/26183680/6f15a4f7-fde0-49fe-8e72-2f91d32df22c)

but it can't be removed again:
![image](https://github.com/radicle-dev/drips-app-v2/assets/26183680/dc424b95-1536-4497-9e4c-7edb77f0d2f4)

**Comment by efstajas** [comment]
@CodeSandwich did you refresh the app? currently it doesn't do that automatically for the new flows. sometimes the subgraph may also be a bit behind…

**Comment by CodeSandwich** [comment]
I think that it could've been a subgraph delay. I've refreshed the page and the stream is gone.
