### ISSUE TITLE
personal Drips List name not visible in streams sections

### ISSUE THREAD

**Issue by xmxanuel** [radicle-dev/drips-app-v2#573]
![personal ](https://github.com/radicle-dev/drips-app-v2/assets/5212495/b5757d62-1300-42a2-b2af-89cf4d70a5b2)

As a user, I want to see the name I gave to my list in the stream section to easily identify the list

**Comment by efstajas** [comment]
https://github.com/radicle-dev/drips-app-v2/issues/520
