### ISSUE TITLE
Refocus the input field after pressing return and adding an item to the list

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/drips-app-v2#594]
I'm adding multiple recipients here and each time I press return to add someone to the list, i have to reclick on the input field to type again.

<img width="756" alt="image" src="https://github.com/radicle-dev/drips-app-v2/assets/4406983/cb25bfd6-0a26-4c42-92b1-7558a51e430d">

**Comment by efstajas** [comment]
we did have this logic but accidentally only applied it after adding a project, and only after the first one, lol. https://github.com/radicle-dev/drips-app-v2/pull/597 fixes it 👍
