### ISSUE TITLE
Define links (or not) for the "What's new" section

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/drips-app-v2#89]
This section isn’t linked up to anything and is a bit irrelevant
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/4406983/206587974-ecdbf7b0-6c3c-4392-ba8c-77d2f387d4da.png">

- [ ] The Drips team presented at DevCon 22
- [ ] Drips JS-SDK ready for use!
- [ ] Version 0.2 released
- [ ] Drips get-together at EthCC
- [ ] The alpha version of our SDK is released
- [ ] Protocol v2 now on Goerli Testnet

**Comment by efstajas** [comment]
Closing this (for now) given we don't have that section anymore.
